<div class="main-page">
		<?php
			if(isset($_GET['banner'])){
				include("includes/home-banner.php");
			}
			if(isset($_GET['home-about'])){
				include("includes/home-about.php");
			}
			if(isset($_GET['web-project'])){
				include("includes/web-project.php");
			}
			if(isset($_GET['edit-webproject'])){
				include("includes/edit-webproject.php");
			}
			if(isset($_GET['edit-webproject-image'])){
				include("includes/edit-webproject-image.php");
			}
			if(isset($_GET['detete-webproject'])){
				include("includes/detete-webproject.php");
			}
			//===================//
	if(isset($_GET['myskill'])){
				include("includes/about-myskill.php");
			}
	if(isset($_GET['detete-about-skill'])){
				include("includes/delete-about-skill.php");
			}
	//===================//
			if(isset($_GET['graphic-project'])){
				include("includes/graphic-project.php");
			}
			if(isset($_GET['edit-graphicproject'])){
				include("includes/edit-graphicproject.php");
			}
			if(isset($_GET['edit-graphicproject-image'])){
				include("includes/edit-graphicproject-image.php");
			}
			if(isset($_GET['detete-graphicproject'])){
				include("includes/detete-graphicproject.php");
			}
			//===================//
			if(isset($_GET['blog'])){
				include("blog.php");
			}
			if(isset($_GET['inner-blog'])){
				include("includes/inner-blog.php");
			}
			if(isset($_GET['edit-blog-content'])){
				include("includes/edit-blog-content.php");
			}
			if(isset($_GET['edit-blog-image'])){
				include("includes/edit-blog-image.php");
			}
			if(isset($_GET['inner-blog-page'])){
				include("includes/inner-blog-page.php");
			}
			if(isset($_GET['delete-blog'])){
				include("includes/delete-blog.php");
			}
			if(isset($_GET['delete-inner-blog'])){
				include("includes/delete-inner-blog.php");
			}
			?>	
</div>